library("DBI", lib.loc="~/R/win-library/3.0")
library("shiny", lib.loc="~/R/win-library/3.0")
library("ggplot2", lib.loc="~/R/win-library/3.0")
library("RJDBC", lib.loc="~/R/win-library/3.0")
library("rJava", lib.loc="~/R/win-library/3.0")
